version: '3.8'

services:
  backend:
    build: ./property-selling-backend-2
    image: daud772/property-pro-backend
    ports:
      - "3000:3000"
    volumes:
      - ./property-selling-backend-2:/app
    environment:
      - PORT=3000
    working_dir: /app
    command: npm run dev

  frontend:
    build: ./property-selling-frontend
    image: daud772/property-pro-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./property-selling-frontend:/app
    environment:
      - PORT=5173
    working_dir: /app
    command: npm run dev

  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.3.0
    container_name: grafana
    ports:
      - "3100:3000"  # Grafana UI on port 3001
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # default password for Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
    driver: local